version: '2'
services:
  nginx:
      build: ./nginx/
      ports:
          - "80:80"
      links:
          - php
      volumes_from:
          - app

  php:
      build: ./php/
      expose:
          - "9000"
      links:
          - main_db
      volumes_from:
          - app
      environment:
          XDEBUG_CONFIG: remote_host=127.0.0.1

  app:
      build: ./php/
      volumes:
          - "./app:/var/www/html"
      command: "true"

#-------------MainDB-------------------------
  main_db:
      image: "mysql:latest"
      ports:
          - "3306:3306"
      volumes_from:
          - main_db_data
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test

  main_db_data:
      image: "mysql:latest"
      volumes:
          - "./main_db:/var/lib/mysql"
      command: "true"
